export enum TransactionCommits {
  SET_LIST = "SET_LIST",
  SET_ERROR = "SET_ERROR",
  SET_FETCH_LIST = "SET_FETCH_LIST",
  SET_CAN_SHOW_AMOUNT = "SET_CAN_SHOW_AMOUNT",
  SET_SEARCH_BY_TITLE = "SET_SEARCH_BY_TITLE",
  ADD_FILTER = "ADD_FILTER",
  DELETE_FILTER = "DELETE_FILTER",
}
